### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by piubellofelipe** [PowerlineApp/powerline-rn#296]
Powerline refactor planning
Objectives:	
1) Let's make this a scalable, easy to manage app
2) Let's maximize our shared codebase for the web app to make that effort easier in both short and long term
3) Let's improve performance and performance-related user experience as best as we can to make this a world class experience

- [x] Isolate all methods for reusing in web-app (will have to re-do only render functions)
- [x] Move all alerts we currently call to only one alert in "utils" directory (will make a thing or two quicker for web-app too)
- [x]  isolate any inline styles - this will make it easier for web-app too

- [x] Upgrade react-native - (in progress)
- [x] Upgrade redux-persist, redux, router, any core package that might be used in web-app - (in progress)
- [x] Think about performance (react-native-router-flux related, upgrading packages related - we can only know really what's happening about performance once we have everything upgraded)
- [x] Implement frontend caching where it's missing, fix where it's buggy, to avoid useless loadings and have better UX in general - this should also impact performance - in progress
- [x] Drawer performance issues
- [x] App crashes on tour
- [x] Sharing into powerline - optimize UI / UX
- [x] Refactor on the whole data flow on group managing screen
- [x] Group manage screen - search for problems, refactor data flow (related to above)
- [x] Solve the pulse loader problem
- [ ] have a better environment control - dev for debug mode, staging/prod for release mode
- [ ] Make all alerts the same "alert" from "utils" - (progress: 50% done)
- [ ] Fix all unhandled exceptions (showing alert, prevent infinite loadings, etc) - (progress: 50% done)

- [x] UI refactor - font sizing, paddings - we might need to rethink how we want our UI (and also validate ideas with Jesse) (done as it is included in other issue)
- [x] Create a new "Actions" function, for navigating (as we upgrade the react-native version, it might be wise to upgrade / change our routing package) (done as it was not necessary in the end)
- [x] My Profile screen - search for problems (possible UI refactor) - deprioritized (done as it is included in other issue)
- [x] Follow/Unfollow Icons - too small? - talk to Jesse (done as it is included in other issue)
A few more things (related to the above or not) will be added to fulfil all our objectives

- [x] Certify sharing into powerline on Android works
- [x] Certify sharing out of powerline on Android works
- [x] Certify sharing into powerline on ios works
- [x] Certify sharing out of powerline on ios works

edit 1: changed order accordingly with priority
edit 2: added react-native/packages upgrades "in progress" tag
edit 3: added "UI refactor - font sizing, paddings - we might need to rethink how we want our UI"
edit 4: added "Follow/Unfollow Icons" item
edit 5: added drawer related item
edit 6: added tour problem, sharing into powerline problem

**Comment by jterps08** [comment]
Placeholder should be "Custom Code (Optional)"
![image](https://user-images.githubusercontent.com/7582457/35202700-278d6d8a-fef2-11e7-9f6f-f3f3fe2f8323.png)

App crashes after user taps "Let's Go" on last screen of onboarding flow AND, separately, when user taps Share this App from main menu
![image](https://user-images.githubusercontent.com/7582457/35202712-3c482378-fef2-11e7-9d7d-d65ae262551b.png)

Weird Pulser behavior 
![image](https://user-images.githubusercontent.com/7582457/35202718-462d6d4e-fef2-11e7-9995-db38f2377ffd.png)

For new user, My Groups takes a long time to load / spinner shows forever
![image](https://user-images.githubusercontent.com/7582457/35202727-51517364-fef2-11e7-9368-f8265948b753.png)

Can we redirect this to the Add Group / Search group screen rather than the Create Group Screen please?
![image](https://user-images.githubusercontent.com/7582457/35202745-629ec2ca-fef2-11e7-9902-399c067a9fec.png)

Seems that user's / author's name not appearing in feed and no avatar either
![image](https://user-images.githubusercontent.com/7582457/35202758-70ff5b72-fef2-11e7-946f-aacffde1f90c.png)

User's name and avatar appears on Item Detail Screen but with no space between first and last
![image](https://user-images.githubusercontent.com/7582457/35202765-82948498-fef2-11e7-8946-b80342937a70.png)

This might be because the frontend doesn't realize the logged-in user is the same user as the NaN because of the NaN, but I should be able to see my own pics
![image](https://user-images.githubusercontent.com/7582457/35202781-98df0688-fef2-11e7-9d79-288f378d5914.png)

Friends Feed is having issues with avatar and name as well as content of the posts
![image](https://user-images.githubusercontent.com/7582457/35202788-a38be204-fef2-11e7-8bb2-0dbd222c4057.png)

**Comment by jterps08** [comment]
closing for 3.2.0 release

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 12/19/17 - 01/11/18
Work session total: 32:43:29

Grand total: 32:43:29
